name: Python application

# Triggers the workflow on push or pull request events
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Defines the job
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checks out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v3

    # Sets up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you are using

    # Installs dependencies
    - name: Install dependencies
      run: |
        make install

    # Runs the application
    - name: Run the app
      run: |
        make run &
        sleep 10  # Sleep to allow the server to start

    # Tests the application
    - name: Test the app
      run: |
        curl --fail http://localhost:3000 || exit 1
